backend:
  name: github
  repo: i-am-sarath/trending-prompt-web # <-- set this
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "prompts"
    label: "Prompts"
    folder: "src/content/prompts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Prompt Text", name: "prompt", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          [
            "sci-fi",
            "portrait",
            "fantasy",
            "product",
            "logo",
            "anime",
            "general",
          ]
        default: "general"
      - { label: "Tool", name: "tool", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
